version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - NotTheRealWallyx
  assignees:
  - NotTheRealWallyx
  labels:
  - dependencies
